POST HTTP://localhost:9090/beach/create HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmljY2FyZG8gIiwic3VybmFtZSI6IkJyZXNvbGluICIsImJpcnRoZGF5IjoiMTUvMTIvMjAyMyIsImF2YXRhciI6Imh0dHBzOi8vcmVzLmNsb3VkaW5hcnkuY29tL2RiYWNjaXVwZS9pbWFnZS91cGxvYWQvdjE2OTM4NDc3MTIvYXZhdGFyL2F5d240amVzbm5zN3E0cGV5ZTVhLnBuZyIsInR5cGUiOiJQZXJzb25hIiwiaWQiOiI2NGY2MTA5ZWQ0YTBjMTZhNjk0YzU2OWUiLCJpYXQiOjE2OTQ0MzIxOTcsImV4cCI6MTY5NDUxODU5N30.RbfSkETy0oc6ME0FCJFz2fjdjQWMtE6HNapUH4PtYdY

{
    "name": "Matosinhos",
    "type": "Beach break",
    "location": "Matosinhos, Porto, France",
    "level": "Intermedio",
    "image": "https://tse3.mm.bing.net/th?id=OIP.lxUl3RyawfXGf5JwEK5VoAHaE9&pid=Api&P=0&h=180",
    "user": "64f4b0a0f5665018725d8d94"
}

####

GET http://localhost:9090/beach

####
DELETE http://localhost:9090/beach/64f4b0cef5665018725d8d9f